server:
  port: 9500
spring:
  profiles:
    active: dev
  application:
    name: inventory-database-service
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
